services:
  application:
    container_name: application

    build:
      context: .
      
    ports:
      - 8000:8000

    volumes:
      - ./application:/applicaton
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
      
    env_file:
      - ./secrets/.env
      
    depends_on:
      - psql

  psql:
    container_name: psql
    image: postgres:13-alpine

    
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    env_file:
      - ./secrets/.env
      
